services:
  samba:
    image: dockurr/samba@sha256:0272e81926b285f868863691d6bf711812a3da3b8845d48b35a2093c068fb0ee
    container_name: samba
    network_mode: host
    environment:
      UID: ${uid}
      GID: ${gid}
    ports:
      - 445:445
    volumes:
      - ${docker_volume_path}/samba/smb.conf:/etc/samba/smb.conf
      - ${docker_volume_path}/samba/users.conf:/etc/samba/users.conf
      - /${zfs_pool_name}/OneDriveDS/Pictures/:/shares/onedrive_photos:rw
      - /${zfs_pool_name}/Videos/TV:/shares/Media/Tv:rw
      - /${zfs_pool_name}/Musique:/shares/Media/Music:rw
      - /qbittorrent-staging/automatic_ripping_machine/media/:/shares/arm:rw
    restart: always
