services:
  cloudflared:
    image: cloudflare/cloudflared:latest@sha256:12ff5c6992a9863db4da270746af7c244bcaee49353039af8104268a18d6c4f0
    network_mode: "host"
    container_name: cloudflared_tunnel
    command: tunnel run --token ${cloudflare_tunnel_token}
    environment:
      TZ: ${TZ}
