services:
  cloudflared:
    image: cloudflare/cloudflared:latest@sha256:ba461b8aa9c042156dbd39c38657fe7431bafa063220eab8d5330a523863da9f
    network_mode: "host"
    container_name: cloudflared_tunnel
    command: tunnel run --token ${cloudflare_tunnel_token}
    environment:
      TZ: ${TZ}
