services:
  nginx:
    image: nginx:1-alpine@sha256:4a73073bd557c65b759505da037898b61f1be6cbcc3c2c3aeac22d2a470c1752
    container_name: nginx
    ports:
      - ${nginx_file_server_port}:80
    networks:
      - nginx_static
    environment:
      TZ: ${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`${nginx_file_server_name}.${public_domain_name}`)
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.tls=true
      - traefik.http.services.nginx.loadbalancer.server.port=80
    volumes:
      - ${nginx_file_server_shared_file_path}:/mnt/share/${nginx_file_server_shared_file_name}:ro
      - ${docker_volume_path}/nginx/etc/nginx/conf.d:/etc/nginx/conf.d

networks:
  nginx_static:
    name: nginx_network
    driver: bridge
