services:

  db:
    image: library/mariadb:latest@sha256:759869cb6f003234a95c6384cdee245b4bce7de26913fe607a8110362c0c007d
    restart: always
    networks:
      - mariadb
    container_name: mariadb
    ports:
      - 3312:3306
    labels:
      - traefik.enable=true
      - traefik.http.routers.mariadb.rule=Host(`mariadb.${public_domain_name}`) || Host(`mariadb.${local_domain_name}`)
      - traefik.http.routers.mariadb.entrypoints=web
      - traefik.http.services.mariadb.loadbalancer.server.port=3306
    volumes:
      - ${docker_volume_path}/mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: ${mariadb_user}
      MARIADB_PASSWORD: ${mariadb_password}
      MARIADB_ROOT_PASSWORD: ${mariadb_root_password}
      MARIADB_AUTO_UPGRADE: ${mariadb_auto_upgrade}

  adminer:
    image: library/adminer:latest@sha256:890cffec7caa20159fb6f68c1a521b2e5879f7314f4845d4ebca7cc1cf145971
    networks:
      - mariadb
    restart: always
    ports:
      - 8306:8080
    labels:
    - traefik.enable=true
    - traefik.http.routers.mariaadmin.rule=Host(`mariaadmin.${public_domain_name}`) || Host(`mariaadmin.${local_domain_name}`)
    - traefik.http.routers.mariaadmin.entrypoints=web
    - traefik.http.services.mariaadmin.loadbalancer.server.port=8080

networks:
  mariadb:
    driver: bridge
