services:

  db:
    image: library/mariadb:latest@sha256:b1c7bf836e64ed9406a8984af29509f40089d55cea14b32f12c4726a1f17104b
    restart: always
    networks:
      - mariadb
    container_name: mariadb
    ports:
      - 3312:3306
    labels:
      - traefik.enable=true
      - traefik.http.routers.mariadb.rule=Host(`mariadb.${public_domain_name}`) || Host(`mariadb.${local_domain_name}`)
      - traefik.http.routers.mariadb.entrypoints=web
      - traefik.http.services.mariadb.loadbalancer.server.port=3306
    volumes:
      - ${docker_volume_path}/mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: ${mariadb_user}
      MARIADB_PASSWORD: ${mariadb_password}
      MARIADB_ROOT_PASSWORD: ${mariadb_root_password}
      MARIADB_AUTO_UPGRADE: ${mariadb_auto_upgrade}

  adminer:
    image: library/adminer:latest@sha256:946244aed5d70cd17b122c5481a1b776e5b138f5c7b1a3b854cd74d8d99b8b88
    networks:
      - mariadb
    restart: always
    ports:
      - 8306:8080
    labels:
    - traefik.enable=true
    - traefik.http.routers.mariaadmin.rule=Host(`mariaadmin.${public_domain_name}`) || Host(`mariaadmin.${local_domain_name}`)
    - traefik.http.routers.mariaadmin.entrypoints=web
    - traefik.http.services.mariaadmin.loadbalancer.server.port=8080

networks:
  mariadb:
    driver: bridge
