services:

  db:
    image: library/mariadb:latest@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d
    restart: always
    networks:
      - mariadb
    container_name: mariadb
    ports:
      - 3312:3306
    labels:
      - traefik.enable=true
      - traefik.http.routers.mariadb.rule=Host(`mariadb.${public_domain_name}`) || Host(`mariadb.${local_domain_name}`)
      - traefik.http.routers.mariadb.entrypoints=web
      - traefik.http.services.mariadb.loadbalancer.server.port=3306
    volumes:
      - ${docker_volume_path}/mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: ${mariadb_user}
      MARIADB_PASSWORD: ${mariadb_password}
      MARIADB_ROOT_PASSWORD: ${mariadb_root_password}
      MARIADB_AUTO_UPGRADE: ${mariadb_auto_upgrade}

  adminer:
    image: library/adminer:latest@sha256:b87a22863ed8c18437c7241a5d39ae2e05669d4d2eb9d78591d5087a09258bc8
    networks:
      - mariadb
    restart: always
    ports:
      - 8306:8080
    labels:
    - traefik.enable=true
    - traefik.http.routers.mariaadmin.rule=Host(`mariaadmin.${public_domain_name}`) || Host(`mariaadmin.${local_domain_name}`)
    - traefik.http.routers.mariaadmin.entrypoints=web
    - traefik.http.services.mariaadmin.loadbalancer.server.port=8080

networks:
  mariadb:
    driver: bridge
